#!/usr/bin/env python3
from __future__ import annotations

import argparse
import asyncio
import json

import httpx


async def main() -> None:
    parser = argparse.ArgumentParser(description="git2mcp example: sync + commit")
    parser.add_argument("--base-url", default="http://localhost:8081")
    parser.add_argument("--repo-id", required=True)
    parser.add_argument("--source-path", required=True)
    parser.add_argument("--branch", default="main")
    args = parser.parse_args()

    async with httpx.AsyncClient(timeout=120.0) as client:
        sync = await client.post(
            f"{args.base_url}/repos/sync",
            json={
                "repo_id": args.repo_id,
                "source_path": args.source_path,
                "branch": args.branch,
            },
        )
        sync.raise_for_status()

        commit = await client.post(
            f"{args.base_url}/repos/{args.repo_id}/commit",
            json={
                "message": "docs(mcp): add git2mcp example note",
                "changes": [
                    {
                        "path": ".mcp/example-note.md",
                        "content": "# Example\n\nGenerated by git2mcp example script.\n",
                        "mode": "update",
                    }
                ],
                "author_name": "git2mcp-example",
                "author_email": "git2mcp@example.local",
            },
        )
        commit.raise_for_status()

        tests = await client.post(
            f"{args.base_url}/repos/{args.repo_id}/run-tests",
            json={"command": "python3 -m compileall -q ."},
        )
        tests.raise_for_status()

    result = {
        "sync": sync.json(),
        "commit": commit.json(),
        "tests": tests.json(),
    }
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
