#!/usr/bin/env python3
"""git2mcp example: dry-run vs execute with auto-revert on failing tests.

Usage:
    python3 git2mcp/examples/04_dry_run_vs_execute.py \
        --repo-id team/sample \
        --source-path /path/to/repo \
        --dry-run

    python3 git2mcp/examples/04_dry_run_vs_execute.py \
        --repo-id team/sample \
        --source-path /path/to/repo \
        --execute
"""

from __future__ import annotations

import argparse
import asyncio
import json

import httpx


PLANNED_EDITS = [
    {
        "path": ".mcp/refactor-note.md",
        "content": "# Refactor\n\nGenerated by 04_dry_run_vs_execute example.\n",
        "mode": "update",
    },
]


async def run(args: argparse.Namespace) -> dict:
    async with httpx.AsyncClient(timeout=120.0) as client:
        sync = await client.post(
            f"{args.base_url}/repos/sync",
            json={
                "repo_id": args.repo_id,
                "source_path": args.source_path,
                "branch": args.branch,
            },
        )
        sync.raise_for_status()

        if args.dry_run:
            return {
                "mode": "dry_run",
                "sync": sync.json(),
                "planned_edits": PLANNED_EDITS,
            }

        commit = await client.post(
            f"{args.base_url}/repos/{args.repo_id}/commit",
            json={
                "message": "chore(mcp): autonomous refactor commit",
                "changes": PLANNED_EDITS,
                "author_name": "git2mcp-bot",
                "author_email": "git2mcp@local",
            },
        )
        commit.raise_for_status()
        commit_payload = commit.json()

        tests = await client.post(
            f"{args.base_url}/repos/{args.repo_id}/run-tests",
            json={"command": args.test_command},
        )
        tests.raise_for_status()
        tests_payload = tests.json()

        if tests_payload.get("ok"):
            return {
                "mode": "execute",
                "sync": sync.json(),
                "commit": commit_payload,
                "tests": tests_payload,
                "reverted": False,
            }

        reset = await client.post(
            f"{args.base_url}/repos/{args.repo_id}/reset",
            json={"ref": "HEAD~1", "mode": "hard"},
        )
        reset.raise_for_status()

        return {
            "mode": "execute",
            "sync": sync.json(),
            "commit": commit_payload,
            "tests": tests_payload,
            "reverted": True,
            "reset": reset.json(),
        }


def main() -> None:
    parser = argparse.ArgumentParser(description="git2mcp dry-run vs execute with auto-revert")
    parser.add_argument("--base-url", default="http://localhost:8081")
    parser.add_argument("--repo-id", required=True)
    parser.add_argument("--source-path", required=True)
    parser.add_argument("--branch", default="main")
    parser.add_argument("--test-command", default="python3 -m compileall -q .")

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--dry-run", action="store_true")
    group.add_argument("--execute", action="store_true")

    args = parser.parse_args()
    result = asyncio.run(run(args))
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
