"""Registry of semcod CLI tools invocable via /tools/run."""

from __future__ import annotations

from typing import Any

SUPPORTED_TOOLS: dict[str, dict[str, Any]] = {
    "sumd": {
        "package": "sumd",
        "binary": "sumd",
        "description": "SUMD - Structured Unified Markdown Descriptor (project doc generator)",
        "default_subcommand": "scan",
        "default_args": [".", "--fix", "--workspace-mode", "--profile", "refactor"],
        "fallback_subcommand": "map",
        "fallback_args": ["."],
        "key_outputs": [
            "SUMD.md",
            "SUMR.md",
            "project/map.toon.yaml",
            "SUMR.json",
        ],
        "summary_files": ["SUMR.md", "SUMD.md", "project/map.toon.yaml"],
    },
    "code2llm": {
        "package": "code2llm",
        "binary": "code2llm",
        "description": "Static + dynamic code analyzer (TOON, call graphs, metrics)",
        "extra_pip_deps": ["psutil"],
        "default_subcommand": None,
        "default_args": [".", "-f", "toon", "-o", "code2llm_output"],
        "key_outputs": [
            "code2llm_output/map.toon.yaml",
            "code2llm_output/calls.yaml",
            "code2llm_output/analysis.toon.yaml",
        ],
        "summary_files": ["code2llm_output/map.toon.yaml"],
    },
    "code2docs": {
        "package": "code2docs",
        "binary": "code2docs",
        "description": "Auto-generate project documentation from source code",
        "default_subcommand": "generate",
        "default_args": ["."],
        "key_outputs": ["docs/index.md", "code2docs.yaml"],
        "summary_files": ["docs/index.md"],
    },
    "code2logic": {
        "package": "code2logic",
        "binary": "code2logic",
        "description": "Extract business logic and decision flow from code",
        "default_subcommand": None,
        "default_args": ["."],
        "key_outputs": [],
        "summary_files": [],
    },
    "code2schema": {
        "package": "code2schema",
        "binary": "code2schema",
        "description": "Infer JSON/SQL/OpenAPI schemas from code",
        "default_subcommand": None,
        "default_args": ["."],
        "key_outputs": [],
        "summary_files": [],
    },
    "redsl": {
        "package": "redsl",
        "binary": "redsl",
        "description": "reDSL - automated refactoring planner",
        "default_subcommand": "refactor",
        "default_args": [".", "-n", "10", "-f", "json", "--dry-run"],
        "key_outputs": [
            "redsl_refactor_plan.md",
            "redsl_refactor_plan.toon.yaml",
            "redsl_refactor_report.md",
        ],
        "summary_files": ["redsl_refactor_plan.md"],
    },
    "redup": {
        "package": "redup",
        "binary": "redup",
        "description": "Detect duplicated/redundant code blocks",
        "default_subcommand": "scan",
        "default_args": ["."],
        "key_outputs": ["redup_report.md", "redup_report.yaml"],
        "summary_files": ["redup_report.md"],
    },
    "regres": {
        "package": "regres",
        "binary": "regres",
        "description": "Regression test discovery and grouping",
        "default_subcommand": None,
        "default_args": ["."],
        "key_outputs": [],
        "summary_files": [],
    },
    "regix": {
        "package": "regix",
        "binary": "regix",
        "description": "Regex-based code grep + transform",
        "default_subcommand": None,
        "default_args": ["."],
        "key_outputs": [],
        "summary_files": [],
    },
    "vallm": {
        "package": "vallm",
        "binary": "vallm",
        "description": "Validate LLM outputs against schemas/rules",
        "default_subcommand": None,
        "default_args": ["."],
        "key_outputs": [],
        "summary_files": [],
    },
    "pyqual": {
        "package": "pyqual",
        "binary": "pyqual",
        "description": "Python quality assessor",
        "default_subcommand": "init",
        "default_args": ["--profile", "python"],
        "key_outputs": ["pyqual.yaml"],
        "summary_files": ["pyqual.yaml"],
    },
    "domd": {
        "package": "domd",
        "binary": "domd",
        "description": "Project Markdown documentation auditor",
        "default_subcommand": None,
        "default_args": ["."],
        "key_outputs": [],
        "summary_files": [],
    },
    "clickmd": {
        "package": "clickmd",
        "binary": "clickmd",
        "description": "Clickable interactive Markdown renderer",
        "default_subcommand": None,
        "default_args": ["."],
        "key_outputs": [],
        "summary_files": [],
    },
    "algitex": {
        "package": "algitex",
        "binary": "algitex",
        "description": "Algorithmic / textual analysis pipeline",
        "default_subcommand": None,
        "default_args": ["."],
        "key_outputs": [],
        "summary_files": [],
    },
}
