"""Configuration management for .env files."""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Dict, Optional


class EnvConfig:
    """Manages .env file configuration."""

    def __init__(self, env_path: str | Path = ".env"):
        self.env_path = Path(env_path)
        self._data: Dict[str, str] = {}
        self._load()

    def _load(self) -> None:
        """Load existing .env file if it exists."""
        if self.env_path.exists():
            with open(self.env_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#"):
                        # Handle export KEY=value syntax
                        if line.startswith("export "):
                            line = line[7:]
                        match = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)=(.*)$', line)
                        if match:
                            key, value = match.groups()
                            # Remove quotes if present
                            if (value.startswith('"') and value.endswith('"')) or \
                               (value.startswith("'") and value.endswith("'")):
                                value = value[1:-1]
                            self._data[key] = value

    def get(self, key: str, default: str | None = None) -> str | None:
        """Get configuration value."""
        # First check environment, then file
        return os.getenv(key) or self._data.get(key, default)

    def set(self, key: str, value: str) -> None:
        """Set configuration value."""
        self._data[key] = value

    def remove(self, key: str) -> None:
        """Remove configuration key."""
        self._data.pop(key, None)

    def _format_value(self, key: str, value: str) -> str:
        """Format a value for .env file - don't quote numeric values."""
        # Don't quote numeric values (ports, etc.)
        if value.isdigit():
            return value
        # Don't quote boolean values
        if value.lower() in ("true", "false"):
            return value
        # Don't quote values that already have quotes
        if (value.startswith('"') and value.endswith('"')) or \
           (value.startswith("'") and value.endswith("'")):
            return value
        # Quote string values
        return f'"{value}"'

    def save(self, create_backup: bool = True) -> None:
        """Save configuration to .env file."""
        if create_backup and self.env_path.exists():
            backup_path = self.env_path.with_suffix(".env.backup")
            backup_path.write_text(self.env_path.read_text(), encoding="utf-8")

        lines = []

        # Add header
        lines.append(f"# Generated by env2mcp v0.1.0")
        lines.append(f"# {self.env_path.absolute()}")
        lines.append("")

        # GitHub configuration
        if any(k.startswith("GITHUB_") for k in self._data.keys()):
            lines.append("# GitHub Configuration")
            for key in sorted(self._data.keys()):
                if key.startswith("GITHUB_"):
                    value = self._data[key]
                    lines.append(f'{key}={self._format_value(key, value)}')
            lines.append("")

        # OpenRouter / LLM Configuration
        if any(k in ("OPENROUTER_API_KEY", "LLM_MODEL", "LLM_PROVIDER") for k in self._data.keys()):
            lines.append("# LLM Configuration")
            for key in ["OPENROUTER_API_KEY", "LLM_MODEL", "LLM_PROVIDER"]:
                if key in self._data:
                    value = self._data[key]
                    lines.append(f'{key}={self._format_value(key, value)}')
            lines.append("")

        # MCP / WebUI Configuration
        if any(k in ("WEBUI_API_KEY", "MCP_GATEWAY_URL") for k in self._data.keys()):
            lines.append("# MCP Configuration")
            for key in ["WEBUI_API_KEY", "MCP_GATEWAY_URL", "GIT_PROXY_URL"]:
                if key in self._data:
                    value = self._data[key]
                    lines.append(f'{key}={self._format_value(key, value)}')
            lines.append("")

        # Other keys
        other_keys = [k for k in self._data.keys()
                      if not k.startswith("GITHUB_")
                      and k not in ("OPENROUTER_API_KEY", "LLM_MODEL", "LLM_PROVIDER",
                                    "WEBUI_API_KEY", "MCP_GATEWAY_URL", "GIT_PROXY_URL")]
        if other_keys:
            lines.append("# Other Configuration")
            for key in sorted(other_keys):
                value = self._data[key]
                lines.append(f'{key}={self._format_value(key, value)}')
            lines.append("")

        self.env_path.write_text("\n".join(lines), encoding="utf-8")

    def __contains__(self, key: str) -> bool:
        return key in self._data or key in os.environ

    def __getitem__(self, key: str) -> str:
        value = self.get(key)
        if value is None:
            raise KeyError(key)
        return value

    def __setitem__(self, key: str, value: str) -> None:
        self.set(key, value)

    def items(self):
        """Return all configuration items."""
        # Merge env and file data, env takes precedence
        result = dict(self._data)
        for key, value in os.environ.items():
            if not key.startswith("_"):  # Skip private vars
                result[key] = value
        return result.items()


def load_env(env_path: str | Path = ".env") -> EnvConfig:
    """Load .env file configuration."""
    return EnvConfig(env_path)


def save_env(config: EnvConfig, create_backup: bool = True) -> None:
    """Save configuration to file."""
    config.save(create_backup=create_backup)
